title:            Knowheretogo
tagline:          Simple.
description:      A bit of anything and everything
canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Stephen Oung
  avatar:         avatar.png
  bio:            "A bit of everything"
  email:          stefou.ca@gmail.com
  github:         stef0u
  flickr:         https://www.flickr.com/photos/stephen-oung/
  location:       "Buffalo, NY"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: notes
    url: /notes
  - title: travel
    url: /travel
  - title: pictures
    url: https://www.flickr.com/photos/stephen-oung/
    external: true
  - title: Who??
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
